import type { Scenario } from './domain'
import { defaultConfig } from './domain'

export const scenarios: Scenario[] = [
  {
    id: 'viewer-sql',
    name: 'Viewer querying SQL',
    description: 'Workspace Viewer reaches the SQL endpoint with ReadData but has no direct OneLake/Spark read.',
    config: { ...defaultConfig, action: 'query-sql' },
  },
  {
    id: 'shared-restricted',
    name: 'Sharing-only restricted reader',
    description: 'A nonmember has item Read and a scoped OneLake role with row and column restrictions.',
    config: { ...defaultConfig, workspaceRole: 'none', itemRead: true, readData: false, defaultReader: false, oneLakeRead: true, rowFilter: true, hiddenColumns: true, action: 'read-onelake' },
  },
  {
    id: 'sql-deny',
    name: 'SQL DENY, OneLake allowed',
    description: 'SQL SELECT is denied even though a OneLake role still authorizes direct data access.',
    config: { ...defaultConfig, workspaceRole: 'none', itemRead: true, readData: false, defaultReader: false, oneLakeRead: true, sqlSelect: true, sqlDenySelect: true, action: 'query-sql' },
  },
  {
    id: 'sql-user-identity',
    name: 'SQL with user identity',
    description: 'The SQL endpoint passes the signed-in user to OneLake, so a OneLake role—not SQL SELECT—controls table access.',
    config: { ...defaultConfig, workspaceRole: 'viewer', sqlAccessMode: 'user', readData: true, sqlSelect: false, oneLakeRead: true, rowFilter: true, action: 'query-sql' },
  },
  {
    id: 'group-broadening',
    name: 'Nested group broadens access',
    description: 'A group-derived Contributor role makes a custom restricted-reader role ineffective as a boundary.',
    config: { ...defaultConfig, workspaceRole: 'contributor', viaGroup: true, oneLakeRead: true, rowFilter: true, action: 'read-onelake' },
  },
  {
    id: 'scoped-write',
    name: 'Scoped OneLake write',
    description: 'A sharing-only user combines item Read with OneLake ReadWrite for Spark/OneLake writes.',
    config: { ...defaultConfig, workspaceRole: 'none', itemRead: true, readData: false, defaultReader: false, oneLakeReadWrite: true, action: 'write-spark' },
  },
  {
    id: 'shortcut-target',
    name: 'Shortcut target missing',
    description: 'The user can reach the Lakehouse but passthrough access fails at the shortcut target.',
    config: { ...defaultConfig, workspaceRole: 'viewer', shortcut: 'passthrough', shortcutTargetAccess: false, action: 'read-onelake' },
  },
  {
    id: 'reshare',
    name: 'Explicit Reshare',
    description: 'A Viewer can share an item only because an explicit Reshare permission was granted.',
    config: { ...defaultConfig, workspaceRole: 'viewer', reshare: true, action: 'reshare-manage' },
  },
  {
    id: 'semantic-sso-filtered',
    name: 'Direct Lake SSO with OneLake filtering',
    description: 'A report consumer has model Read and source item Read, while OneLake restricts the rows and columns returned through Direct Lake.',
    config: {
      ...defaultConfig,
      workspaceRole: 'none',
      itemRead: true,
      readData: false,
      defaultReader: false,
      oneLakeRead: true,
      rowFilter: true,
      hiddenColumns: true,
      semanticModelPermission: 'read',
      semanticModelIdentity: 'sso',
      action: 'view-report',
    },
  },
  {
    id: 'semantic-sso-source-denied',
    name: 'Model Read but SSO source denied',
    description: 'The semantic model is reachable, but the current user cannot reach the source Lakehouse required by Direct Lake SSO.',
    config: {
      ...defaultConfig,
      workspaceRole: 'none',
      itemRead: false,
      readData: false,
      readAll: false,
      defaultReader: false,
      oneLakeRead: true,
      semanticModelPermission: 'read',
      semanticModelIdentity: 'sso',
      action: 'query-semantic-model',
    },
  },
  {
    id: 'semantic-fixed-identity',
    name: 'Fixed identity isolates the source',
    description: 'A consumer queries the semantic model without direct Lakehouse access because the fixed connection identity reads OneLake.',
    config: {
      ...defaultConfig,
      workspaceRole: 'none',
      itemRead: false,
      readData: false,
      readAll: false,
      defaultReader: false,
      oneLakeRead: false,
      semanticModelPermission: 'read',
      semanticModelIdentity: 'fixed',
      fixedIdentitySourceAccess: true,
      semanticModelRls: true,
      semanticModelRoleAssigned: true,
      action: 'query-semantic-model',
    },
  },
  {
    id: 'semantic-layered-security',
    name: 'OneLake and model security intersect',
    description: 'OneLake first filters source rows, then semantic-model RLS and OLS further restrict the result for the report consumer.',
    config: {
      ...defaultConfig,
      workspaceRole: 'none',
      itemRead: true,
      readData: false,
      defaultReader: false,
      oneLakeRead: true,
      rowFilter: true,
      semanticModelPermission: 'read',
      semanticModelIdentity: 'sso',
      semanticModelRls: true,
      semanticModelOls: true,
      semanticModelRoleAssigned: true,
      action: 'query-semantic-model',
    },
  },
  {
    id: 'semantic-build-metadata',
    name: 'Build exposes model metadata',
    description: 'Build allows report authoring and XMLA access, including discovery of hidden fields and secured object names in model metadata.',
    config: {
      ...defaultConfig,
      workspaceRole: 'none',
      itemRead: true,
      readData: false,
      defaultReader: false,
      oneLakeRead: true,
      semanticModelPermission: 'build',
      semanticModelIdentity: 'sso',
      action: 'build-report',
    },
  },
  {
    id: 'semantic-write-bypass',
    name: 'Model Write bypasses model RLS',
    description: 'An explicit model Write grant bypasses semantic-model RLS, while the effective source identity must still pass OneLake authorization.',
    config: {
      ...defaultConfig,
      workspaceRole: 'none',
      itemRead: true,
      readData: false,
      defaultReader: false,
      oneLakeRead: true,
      semanticModelPermission: 'write',
      semanticModelIdentity: 'sso',
      semanticModelRls: true,
      semanticModelRoleAssigned: false,
      action: 'query-semantic-model',
    },
  },
  {
    id: 'semantic-owner-framing',
    name: 'Owner cannot frame the model',
    description: 'The refresh initiator has Write, but Direct Lake framing fails because the semantic-model owner cannot read the source tables.',
    config: {
      ...defaultConfig,
      semanticModelPermission: 'write',
      semanticModelIdentity: 'fixed',
      fixedIdentitySourceAccess: true,
      semanticModelOwnerSourceAccess: false,
      action: 'refresh-semantic-model',
    },
  },
  {
    id: 'semantic-cross-workspace',
    name: 'Model and source in separate workspaces',
    description: 'Viewer access to the model workspace is combined with explicit source item Read and a scoped OneLake role in another workspace.',
    config: {
      ...defaultConfig,
      semanticWorkspaceRole: 'viewer',
      semanticModelPermission: 'none',
      workspaceRole: 'none',
      itemRead: true,
      readData: false,
      defaultReader: false,
      oneLakeRead: true,
      semanticModelIdentity: 'sso',
      action: 'view-report',
    },
  },
]
